Outpout better diagnostics if a plugin fails to initialize.
AntelopeIO/appbase pull request #15
Opened 2023-03-30 22:53 UTC by greg7mdp

Resolves #14

2023-03-31 13:11 UTC, heifner requested changes

2023-03-31 13:50 UTC, greg7mdp commented on application_base.cpp
>        std::cerr << "Failed to initialize\n";
Thanks, I updated the message. It now looks like:

```
appbase: exception thrown during plugin "pluginB" initialization.
divide by zero
```

2023-03-31 13:51 UTC, heifner approved these changes

2023-03-31 14:06 UTC, greg7mdp commented
@heifner Thanks for approving. FYI in case you want to have another look, I updated the PR to extend the try/catch block (exceptions in the other loop for plugin initialization were not caught).

2023-03-31 14:18 UTC, heifner approved these changes

2023-04-04 21:19 UTC, linh2931 approved these changes

2023-04-04 22:24 UTC, merged